trigger:
- main

pool: 
 vmImage: 'ubuntu-latest'

variables:
  terraformWorkingDirectory: 'Terraform/Landing_Zone_Monolithic_Services_Infra/Env/Prod' #My code location on the github

#Stage1 Terraform Init 
stages:  
- stage : init 
  displayName: Terraform Init
  jobs:  
  - job: Terraform_Init 
    steps:
    - checkout: self 
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.11.3'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'Terraform/Landing_Zone_Monolithic_Services_Infra/Env/Prod' #My code location on the github

#Stage2 Terraform Validate
- stage: validate
  displayName: Terraform Validate
  jobs:
  - job: ValidateJob
    steps:
    - checkout: self
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'Terraform/Landing_Zone_Monolithic_Services_Infra/Env/Prod' #My code location on the github
    - task: TerraformTask@5
      displayName: Terraform Format (FMT)
      inputs:
        provider: 'azurerm'
        command: 'custom'
        commandOptions: 'fmt'
        outputTo: 'console'
    