trigger:
- main

pool: Default
steps:
- checkout: self
- task: TerraformInstaller@1
  displayName: Install_Terraform
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terrform/Landing_Zone_Monolithic_Services_Infra/Env/Prod'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terrform/Landing_Zone_Monolithic_Services_Infra/Env/Prod'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terrform/Landing_Zone_Monolithic_Services_Infra/Env/Prod'

