apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  selector:
    todo: app 
  ports:
  - port: 9090
    targetPort: 80
    nodePort: 32767 #Port Must be between 30000-32767
  type: NodePort