apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: myapp
      image: sonambewafaa/photos-app:v2
      ports:
        - containerPort: 8501
      volumeMounts: 
        - name: my-azure-volume
          mountPath: /app/photos
          readOnly: false
  volumes:  
  - name: my-azure-volume
    persistentVolumeClaim:  
      claimName: pvc1