apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv

spec:
  accessModes:
    - ReadWriteMany 
  azureFile:
    secretName: pv1-secrets
    shareName:  myphotos
    readOnly: false
  capacity:	
    storage: 4Gi
  persistentVolumeReclaimPolicy:  Retain
  volumeMode: Filesystem
  storageClassName: ganeshclassname

